groups:
- name: example
  rules:
  - alert: ServerUnresponsive
    expr: up == 0
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: "Server {{ $labels.instance }} down"
      description: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 1 minute."

  - alert: HighResponseTime
    expr: http_request_duration_seconds > 1
    labels:
      severity: warning
    annotations:
      summary: "High response time on {{ $labels.instance }}"
      description: "The response time on {{ $labels.instance }} is greater than 1 second."
