global:
  scrape_interval: 15s

rule_files:
  - /etc/prometheus/alert.rules.yml

scrape_configs:
  - job_name: 'flask'
    static_configs:
      - targets: ['flask_app:5000']

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']